version: '3.8'

services:
  ktor-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - ktor-network
    depends_on:
      - postgres-db
    environment:
      POSTGRES_URL: "jdbc:postgresql://postgres-db:5433/postgres"
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
      PORT: 8080

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_DB: "postgres"
    ports:
      - "5433:5432"
    networks:
      - ktor-network

networks:
  ktor-network:
